### ISSUE TITLE
2020.04 Release not have EFI folder .zip file 

### ISSUE THREAD

**Issue by t3s8r8** [williambj1/Hackintosh-Asus-ROG-Laptop-Coffee-Lake#5]
Hi, I might wanna to try out your new (or newer) efi folder . zip file from yours but I see knowhere to download it. Can you update it to be appeared ? Thanks <3

**Comment by williambj1** [comment]
WIP

**Comment by t3s8r8** [comment]
> WIP

Ah I see. Thanks !

**Comment by williambj1** [comment]
@t3s8r8 

There are some bugs right now in the release, AppleALC is oversimplified and it doesn't work, OpenCanopy resources are missing. You could manually run the script to build the EFI if you want but you'll have to make some modifications to make it work properly.
