### ISSUE TITLE
Can't Make It work with gx701gx

### ISSUE THREAD

**Issue by claudios91** [williambj1/Hackintosh-Asus-ROG-Laptop-Coffee-Lake#7]
Hello! Thank you so much for you hard work. I've got an issue that I believe is related to NVMe 1Tb samsung PM981.
I can't use OpenCore because it won't even start the boot sequence, even if nvmefix is working better with it. So i booted up with clover (changed usbfix to usbinjectall but i've no trackpad working) and I manage to boot the install, I've installed it but as soon as i try to boot the second part of installing from my ssd it just hangs at half of the process and then reboot. I've tried with Catalina and with Mojave but still no success. Do you have special files for gx701? Thank you so much.

**Comment by williambj1** [comment]
Well, just replace it, pm981 is pure $h!t when it comes with macOS. Your issue has nothing to do with my configuration plist files, and I don't have any related patches, Maybe consider asking help from other forums.
